version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: memory
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    image: conecta-memory:latest
    container_name: conecta-memory
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/memory?createDatabaseIfNotExist=true&useSSL=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql-data:
